name: Testing workflow run
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      prnum:
        required: true
        type: string

jobs:
  testing-automerge:
    runs-on: ubuntu-latest
    name: Validate Dev PR

    steps:
      - name: print a message
        run: echo "running pr-jira-action/sharedwf.yml with parameters name:${{ inputs.username }} and pr:${{ inputs.prnum }}"
